// SharePoint upload extension
//
// Uploads files generated by this run (e.g. the PPT from the ppt extension)
// to a SharePoint document library using the Microsoft Graph API with
// app-only (client credentials) authentication.
//
// Toggle: set SHAREPOINT_ENABLED=true in .env — leave unset to skip silently.
//
// Prerequisites — Azure AD app registration:
//   1. portal.azure.com → Azure Active Directory → App registrations → New
//   2. API permissions → Add → Microsoft Graph → Application → Sites.ReadWrite.All
//   3. Grant admin consent for your org
//   4. Certificates & secrets → New client secret → copy the Value
//
// Config (via .env):
//   SHAREPOINT_ENABLED=true
//   SHAREPOINT_TENANT_ID      — found in Azure AD → Overview (the Directory/tenant ID)
//   SHAREPOINT_CLIENT_ID      — app registration → Overview (Application/client ID)
//   SHAREPOINT_CLIENT_SECRET  — the client secret Value you copied above
//   SHAREPOINT_SITE_URL       — full URL to your SharePoint site
//                               e.g. https://myorg.sharepoint.com/sites/Weekly-Reports
//   SHAREPOINT_FOLDER         — folder path within the document library
//                               e.g. Shared Documents/Weekly Status   (no leading slash)
//
// The extension uploads every file stored in data._generatedFiles by earlier
// extensions. Run ppt before sharepoint so there is something to upload.

import fs   from 'fs';
import path from 'path';

const GRAPH = 'https://graph.microsoft.com/v1.0';

// ─── Auth ─────────────────────────────────────────────────────────────────────

async function getToken() {
  const { SHAREPOINT_TENANT_ID: tid, SHAREPOINT_CLIENT_ID: cid, SHAREPOINT_CLIENT_SECRET: secret } = process.env;
  const res = await fetch(
    `https://login.microsoftonline.com/${tid}/oauth2/v2.0/token`,
    {
      method: 'POST',
      body:   new URLSearchParams({
        grant_type: 'client_credentials', client_id: cid,
        client_secret: secret, scope: 'https://graph.microsoft.com/.default',
      }),
    }
  );
  if (!res.ok) throw new Error(`Auth failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return (await res.json()).access_token;
}

// ─── Site resolution ──────────────────────────────────────────────────────────

async function resolveSiteId(token) {
  const raw      = process.env.SHAREPOINT_SITE_URL;
  if (!raw) throw new Error('SHAREPOINT_SITE_URL is not set');
  const { hostname, pathname } = new URL(raw);
  const res = await fetch(`${GRAPH}/sites/${hostname}:${pathname}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error(`Could not resolve site "${raw}" (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return (await res.json()).id;
}

// ─── Upload ───────────────────────────────────────────────────────────────────

async function upload(token, siteId, filePath) {
  const folder   = (process.env.SHAREPOINT_FOLDER || 'Shared Documents').replace(/^\/|\/$/g, '');
  const filename = path.basename(filePath);
  const url      = `${GRAPH}/sites/${siteId}/drive/root:/${folder}/${filename}:/content`;
  const res = await fetch(url, {
    method:  'PUT',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/octet-stream' },
    body:    fs.readFileSync(filePath),
  });
  if (!res.ok) throw new Error(`Upload failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return (await res.json()).webUrl;
}

// ─── Extension interface ──────────────────────────────────────────────────────

export async function generate(data) {
  if (process.env.SHAREPOINT_ENABLED !== 'true') {
    console.log('\nSharePoint upload skipped (SHAREPOINT_ENABLED not set to true)');
    return;
  }

  const missing = ['SHAREPOINT_TENANT_ID', 'SHAREPOINT_CLIENT_ID', 'SHAREPOINT_CLIENT_SECRET', 'SHAREPOINT_SITE_URL']
    .filter(k => !process.env[k]);
  if (missing.length) {
    console.error(`\n❌  SharePoint: missing required env vars — ${missing.join(', ')}`);
    return;
  }

  const files = (data._generatedFiles || []).filter(f => fs.existsSync(f));
  if (!files.length) {
    console.warn('\n⚠  SharePoint: no generated files to upload. Make sure the ppt extension runs before sharepoint.');
    return;
  }

  console.log('\nUploading to SharePoint...');
  try {
    const token  = await getToken();
    const siteId = await resolveSiteId(token);
    for (const filePath of files) {
      const webUrl = await upload(token, siteId, filePath);
      console.log(`  ✓  ${path.basename(filePath)}`);
      console.log(`     ${webUrl}`);
    }
  } catch (e) {
    console.error(`\n❌  SharePoint upload failed — ${e.message.split('\n')[0]}`);
  }
}
